import type { IProduct } from "../../../shared/types/products";


export const products: IProduct[] = [
    {
        id: 1,
        Code: '77777a',
        Name: 'laptop',
        Desc: 'dell',
        BuyPrice: 4700,
        SellPrice: 8000,
        Quantity: 30,
        Unit: 'шт',
        Ordered: 0,
        CategoryId: 1,
        BatchId: 1,
        WarehouseId: 1,
    },
    {
        id: 2,
        Code: '11111a',
        Name: 'Fridge',
        Desc: 'Bosch',
        BuyPrice: 11700,
        SellPrice: 18000,
        Quantity: 40,
        Unit: 'шт',
        Ordered: 0,
        CategoryId: 1,
        BatchId: 1,
        WarehouseId: 1,
    },
    {
        id: 3,
        Code: '22222a',
        Name: 'TV',
        Desc: 'samsung',
        BuyPrice: 2700,
        SellPrice: 4000,
        Quantity: 60,
        Unit: 'шт',
        Ordered: 0,
        CategoryId: 1,
        BatchId: 1,
        WarehouseId: 1,
    },
    {
        id: 4,
        Code: '3333a',
        Name: 'AC',
        Desc: 'LG',
        BuyPrice: 3700,
        SellPrice: 5000,
        Quantity: 10,
        Unit: 'шт',
        Ordered: 0,
        CategoryId: 1,
        BatchId: 1,
        WarehouseId: 1,
    },
    {
        id: 5,
        Code: '4444a',
        Name: 'PC',
        Desc: 'hp',
        BuyPrice: 11700,
        SellPrice: 18000,
        Quantity: 23,
        Unit: 'шт',
        Ordered: 0,
        CategoryId: 1,
        BatchId: 1,
        WarehouseId: 1,
    }
]